### ISSUE TITLE
cv::saliency::Saliency do not have a create function 

### ISSUE THREAD

**Issue by SoonSYJ** [sangwook236/SWDT#1]
When I try to run the code, there is an error said that create() is not a member of cv::saliency::Saliency. Do you have any idea about this error? thank you. 
cv::Ptr<cv::saliency::Saliency> saliencyAlgorithm = cv::saliency::Saliency::create(saliency_algorithm);

**Comment by sangwook236** [comment]
I built and run the code successfully. I think that the version of OpenCV may be different if you cannot build it. Now I am using OpenCV 3.2.0.
If you couldn;t resolve the problem, please let me know.
